// ── Columbia Road · AI Maturity Quiz Webhook ────────────────────────────────
// Paste this into Google Apps Script (script.google.com → New project)
// Deploy as a Web App: Execute as "Me", access "Anyone"
// Copy the deployment URL into the quiz's N8N_WEBHOOK_URL config line
// ─────────────────────────────────────────────────────────────────────────────

const SHEET_ID   = '1XRDP4UB_4Kbdzc_6KAitYoFxSHnuzVRpy7uh2oXsZ5o';
const SHEET_NAME = 'Sheet1';

// Column order in the sheet
const COLUMNS = [
  'submitted_at',
  'name',
  'email',
  'role',
  'team_size',
  // Scoring
  'score',           // rendered as "14/22"
  'score_pct',
  'stage',
  'adoption_score',
  'data_score',
  'governance_score',
  'team_readiness_score',
  'roi_estimate_eur',
  // Business context
  'deal_size',
  'close_rate',
  'admin_time',
  'monthly_leads',
  'lead_to_conv',
  // AI maturity answers
  'ai_tools',
  'ai_agents',
  'ai_integration',
  'data_quality',
  'governance_owner',
  'team_attitude',
  // Priorities
  'top_opportunities',
  'top_blockers',
  'biggest_time_waste',
  'roadmap_headline',
];

// Human-readable header labels (same order as COLUMNS)
const HEADERS = [
  'Submitted at',
  'Name',
  'Email',
  'Role',
  'Team size',
  'Score',
  'Score %',
  'Stage',
  'Adoption score',
  'Data score',
  'Governance score',
  'Team readiness',
  'ROI estimate (€)',
  'Deal size',
  'Close rate',
  'Admin time',
  'Monthly leads',
  'Lead → conv rate',
  'AI tools',
  'AI agents',
  'AI integration',
  'Data quality',
  'Governance owner',
  'Team attitude',
  'Top opportunities',
  'Top blockers',
  'Biggest time waste',
  'Roadmap headline',
  // Filled in post-event by Claude Code
  'Email subject',
  'Email body',
  // Manual tracking
  'Email sent?',
  'Notes',
];

// ── Main handler ─────────────────────────────────────────────────────────────

function doPost(e) {
  try {
    const raw  = e.postData ? e.postData.contents : '{}';
    const data = JSON.parse(raw);

    // ── write_emails: accept email drafts generated by Claude Code ───────────
    if (data.action === 'write_emails') {
      const ss    = SpreadsheetApp.openById(SHEET_ID);
      const sheet = ss.getSheetByName(SHEET_NAME);
      const subjectCol = HEADERS.indexOf('Email subject') + 1;
      const bodyCol    = HEADERS.indexOf('Email body')    + 1;
      const emails = Array.isArray(data.emails) ? data.emails : [];
      emails.forEach(function(item) {
        if (!item.rowIndex || !item.subject || !item.body) return;
        sheet.getRange(item.rowIndex, subjectCol).setValue(item.subject);
        sheet.getRange(item.rowIndex, bodyCol).setValue(item.body);
      });
      return jsonResponse({ status: 'ok', written: emails.length });
    }

    const ss    = SpreadsheetApp.openById(SHEET_ID);
    const sheet = ss.getSheetByName(SHEET_NAME);

    // Write headers on first submission
    if (sheet.getLastRow() === 0) {
      sheet.appendRow(HEADERS);
      styleHeaderRow(sheet);
    }

    // Build data row
    const row = COLUMNS.map(col => {
      if (col === 'score') {
        return (data.score !== undefined && data.score_max !== undefined)
          ? `${data.score}/${data.score_max}`
          : '';
      }
      const val = data[col];
      return val !== undefined && val !== null ? val : '';
    });

    // Append empty cells for Email subject, Email body, Email sent?, Notes
    row.push('', '', '', '');

    sheet.appendRow(row);

    return jsonResponse({ status: 'ok' });

  } catch (err) {
    return jsonResponse({ status: 'error', message: err.message });
  }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function jsonResponse(obj) {
  return ContentService
    .createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}

function styleHeaderRow(sheet) {
  const range = sheet.getRange(1, 1, 1, HEADERS.length);
  range.setFontWeight('bold');
  range.setBackground('#1B3A6B');   // Columbia Road navy
  range.setFontColor('#FFFFFF');
  range.setFontSize(11);
  sheet.setFrozenRows(1);
  sheet.autoResizeColumns(1, HEADERS.length);

  // Highlight the "Email sent?" column in a soft amber so it stands out
  const emailSentCol = HEADERS.indexOf('Email sent?') + 1;
  if (emailSentCol > 0) {
    sheet.getRange(1, emailSentCol).setBackground('#F59E0B');
  }
}

// ── Aggregated results for live dashboard ────────────────────────────────────
// Called by aggregated-results.html via fetch. Returns JSON with CORS headers.

function doGet(e) {
  try {
    const ss    = SpreadsheetApp.openById(SHEET_ID);
    const sheet = ss.getSheetByName(SHEET_NAME);
    const lastRow = sheet.getLastRow();

    const empty = {
      total: 0,
      stage_distribution: {},
      score_pct_buckets: {},
      top_blockers: {}
    };

    // ── action=rows: return participants needing email drafts ────────────────
    // Used by the /generate-emails Claude Code skill — no API key required.
    if (e && e.parameter && e.parameter.action === 'rows') {
      if (lastRow <= 1) return corsJson({ rows: [] });
      const allData      = sheet.getRange(2, 1, lastRow - 1, HEADERS.length).getValues();
      const bodyCol      = HEADERS.indexOf('Email body');
      const submittedCol = COLUMNS.indexOf('submitted_at');
      const rows = [];
      allData.forEach(function(row, i) {
        if (!row[submittedCol]) return;
        if (row[bodyCol]) return; // draft already exists
        rows.push({
          rowIndex:         i + 2,
          name:             row[COLUMNS.indexOf('name')],
          email:            row[COLUMNS.indexOf('email')],
          role:             row[COLUMNS.indexOf('role')],
          team_size:        row[COLUMNS.indexOf('team_size')],
          score:            row[COLUMNS.indexOf('score')],
          score_pct:        row[COLUMNS.indexOf('score_pct')],
          stage:            row[COLUMNS.indexOf('stage')],
          roi:              row[COLUMNS.indexOf('roi_estimate_eur')] || null,
          blockers:         row[COLUMNS.indexOf('top_blockers')]     || null,
          roadmap:          row[COLUMNS.indexOf('roadmap_headline')] || null,
          weakest_category: weakestCategory_(
            row[COLUMNS.indexOf('adoption_score')],
            row[COLUMNS.indexOf('data_score')],
            row[COLUMNS.indexOf('governance_score')],
            row[COLUMNS.indexOf('team_readiness_score')]
          ),
        });
      });
      return corsJson({ rows: rows });
    }

    if (lastRow <= 1) {
      return corsJson(empty);
    }

    // Read all data rows (skip header row 1)
    const data = sheet.getRange(2, 1, lastRow - 1, COLUMNS.length).getValues();

    const stageCol        = COLUMNS.indexOf('stage');
    const scorePctCol     = COLUMNS.indexOf('score_pct');
    const topBlockersCol  = COLUMNS.indexOf('top_blockers');

    const stageDist   = {};
    const scoreBuckets = {};
    const blockerCounts = {};
    let total = 0;

    data.forEach(row => {
      // Skip completely empty rows
      if (!row[COLUMNS.indexOf('submitted_at')]) return;
      total++;

      // Stage distribution
      const stage = row[stageCol];
      if (stage) stageDist[stage] = (stageDist[stage] || 0) + 1;

      // Score % histogram — floor to nearest 10
      const pct = parseInt(row[scorePctCol], 10);
      if (!isNaN(pct)) {
        const bucket = String(Math.floor(pct / 10) * 10);
        scoreBuckets[bucket] = (scoreBuckets[bucket] || 0) + 1;
      }

      // Top blockers — semicolon-separated values
      const blockerStr = row[topBlockersCol];
      if (blockerStr) {
        blockerStr.split(';').forEach(b => {
          const label = b.trim();
          if (label) blockerCounts[label] = (blockerCounts[label] || 0) + 1;
        });
      }
    });

    return corsJson({ total, stage_distribution: stageDist, score_pct_buckets: scoreBuckets, top_blockers: blockerCounts });

  } catch (err) {
    return corsJson({ error: err.message });
  }
}

function corsJson(obj) {
  return ContentService
    .createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}

// ── Email follow-up configuration ─────────────────────────────────────────────
// PRIMARY approach: use the /generate-emails Claude Code skill — no API key needed.
// ALTERNATIVE (fully automated): set ANTHROPIC_API_KEY in Script Properties and
//   run generateFollowUpEmails() directly from the GAS editor.
// Update MEET_URL to the actual booking link before sending.
const MEET_URL = 'https://calendar.app.google/UixxaEZYnSkbLjSG9';

// ── Generate personalised email drafts (automated alternative) ───────────────
// Run in the GAS editor if you prefer fully automated generation via the API.
// Primary approach: use /generate-emails in Claude Code (no API key required).
function generateFollowUpEmails() {
  const ss    = SpreadsheetApp.openById(SHEET_ID);
  const sheet = ss.getSheetByName(SHEET_NAME);
  const lastRow = sheet.getLastRow();

  if (lastRow <= 1) { Logger.log('No data rows.'); return; }

  const apiKey = PropertiesService.getScriptProperties().getProperty('ANTHROPIC_API_KEY');
  if (!apiKey) { Logger.log('ANTHROPIC_API_KEY not set in Script Properties.'); return; }

  const data = sheet.getRange(2, 1, lastRow - 1, HEADERS.length).getValues();

  const subjectCol   = HEADERS.indexOf('Email subject');
  const bodyCol      = HEADERS.indexOf('Email body');
  const submittedCol = COLUMNS.indexOf('submitted_at');
  const adoptionCol  = COLUMNS.indexOf('adoption_score');
  const dataScoreCol = COLUMNS.indexOf('data_score');
  const govCol       = COLUMNS.indexOf('governance_score');
  const teamCol      = COLUMNS.indexOf('team_readiness_score');

  data.forEach(function(row, i) {
    if (!row[submittedCol]) return;  // skip empty rows
    if (row[bodyCol]) return;        // skip rows with draft already

    const rowIndex  = i + 2;
    const firstName = String(row[COLUMNS.indexOf('name')]).split(' ')[0];
    const email     = row[COLUMNS.indexOf('email')];
    const role      = row[COLUMNS.indexOf('role')];
    const teamSize  = row[COLUMNS.indexOf('team_size')];
    const score     = row[COLUMNS.indexOf('score')];
    const scorePct  = row[COLUMNS.indexOf('score_pct')];
    const stage     = row[COLUMNS.indexOf('stage')];
    const roi       = row[COLUMNS.indexOf('roi_estimate_eur')];
    const blockers  = row[COLUMNS.indexOf('top_blockers')];
    const roadmap   = row[COLUMNS.indexOf('roadmap_headline')];
    const weakest   = weakestCategory_(
      row[adoptionCol], row[dataScoreCol], row[govCol], row[teamCol]
    );

    const prompt = emailPrompt_(firstName, role, teamSize, score, scorePct, stage, roi, blockers, roadmap, weakest);

    try {
      const draft = callClaude_(prompt, apiKey);
      sheet.getRange(rowIndex, subjectCol + 1).setValue(draft.subject);
      sheet.getRange(rowIndex, bodyCol + 1).setValue(draft.body);
      Logger.log('Draft written for: ' + email);
    } catch (err) {
      Logger.log('Failed for ' + email + ': ' + err.message);
    }

    Utilities.sleep(1200);
  });

  Logger.log('generateFollowUpEmails done.');
}

function weakestCategory_(adoption, dataScore, governance, team) {
  const cats = [
    { name: 'Adoption & Tooling', val: adoption },
    { name: 'Data Readiness',     val: dataScore },
    { name: 'Governance',         val: governance },
    { name: 'Team Readiness',     val: team },
  ];
  let lowest = null, lowestPct = Infinity;
  cats.forEach(function(c) {
    const parts = String(c.val).split('/');
    if (parts.length === 2) {
      const n = parseFloat(parts[0]), d = parseFloat(parts[1]);
      if (!isNaN(n) && !isNaN(d) && d > 0 && n / d < lowestPct) {
        lowestPct = n / d;
        lowest = c.name;
      }
    }
  });
  return lowest || 'overall maturity';
}

function emailPrompt_(firstName, role, teamSize, score, scorePct, stage, roi, blockers, roadmap, weakest) {
  const roiLine      = roi ? '\n- ROI estimate: €' + roi : '';
  const blockersLine = blockers ? '\n- Top blockers: ' + blockers : '';
  const blockersNote = blockers
    ? '- 1-2 sentences on their biggest blocker with a concrete counter-move\n'
    : '';
  const roiNote = roi
    ? '- 1 sentence: "Based on your inputs, the opportunity is around €' + roi + '."\n'
    : '';

  return 'Write a personalised follow-up email from Columbia Road after an AI maturity ' +
    'assessment event in Stockholm. Tone: direct, specific, no filler — a sharp consultant ' +
    'speaking plainly, not a content generator producing balanced feedback. Target ~220 words. ' +
    'Return ONLY a valid JSON object with two string fields: "subject" and "body". ' +
    'No markdown fences, no other text.\n\n' +
    'Participant:\n' +
    '- Name: ' + firstName + '\n' +
    '- Role: ' + role + '\n' +
    '- Team size: ' + teamSize + '\n' +
    '- Score: ' + score + ' (' + scorePct + '%)\n' +
    '- Stage: ' + stage + '\n' +
    '- Weakest category: ' + weakest +
    blockersLine +
    roiLine + '\n' +
    '- Roadmap headline: ' + roadmap + '\n\n' +
    'Email structure (in this order):\n' +
    '- Subject: "Your AI Maturity score — [short stage label]"\n' +
    '- "Hi ' + firstName + ',"\n' +
    '- 2-3 sentences: their score, stage, one concrete implication for their role/team size\n' +
    '- 1 paragraph on ' + weakest + ': what the gap means and one specific action to take\n' +
    blockersNote +
    roiNote +
    '- Closing: reference the roadmap headline (' + roadmap + ') then: ' +
    '"If you want to talk through where to start, book a slot: ' + MEET_URL + '"\n' +
    '- Sign off: "Columbia Road"\n\n' +
    'Return only the JSON object — nothing else.';
}

function callClaude_(prompt, apiKey) {
  const resp = UrlFetchApp.fetch('https://api.anthropic.com/v1/messages', {
    method: 'post',
    headers: {
      'x-api-key':         apiKey,
      'anthropic-version': '2023-06-01',
      'content-type':      'application/json',
    },
    payload: JSON.stringify({
      model:      'claude-opus-5',
      max_tokens: 1024,
      messages:   [{ role: 'user', content: prompt }],
    }),
    muteHttpExceptions: true,
  });

  if (resp.getResponseCode() !== 200) {
    throw new Error('API ' + resp.getResponseCode() + ': ' + resp.getContentText());
  }

  const result = JSON.parse(resp.getContentText());
  var text = result.content[0].text.trim();
  text = text.replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/, '').trim();
  return JSON.parse(text);
}

// ── Send reviewed drafts ───────────────────────────────────────────────────────
// Run after reviewing the Email body column. Sends rows with a draft but no sent timestamp.
function sendFollowUpEmails() {
  const ss    = SpreadsheetApp.openById(SHEET_ID);
  const sheet = ss.getSheetByName(SHEET_NAME);
  const lastRow = sheet.getLastRow();

  if (lastRow <= 1) { Logger.log('No data rows.'); return; }

  const data = sheet.getRange(2, 1, lastRow - 1, HEADERS.length).getValues();

  const emailCol     = COLUMNS.indexOf('email');
  const submittedCol = COLUMNS.indexOf('submitted_at');
  const subjectCol   = HEADERS.indexOf('Email subject');
  const bodyCol      = HEADERS.indexOf('Email body');
  const sentCol      = HEADERS.indexOf('Email sent?');

  let sent = 0;

  data.forEach(function(row, i) {
    if (!row[submittedCol]) return;  // empty row
    if (!row[bodyCol]) return;       // no draft yet
    if (row[sentCol]) return;        // already sent

    const rowIndex  = i + 2;
    const recipient = row[emailCol];
    const subject   = row[subjectCol];
    const body      = row[bodyCol];

    try {
      GmailApp.sendEmail(recipient, subject, body, { name: 'Columbia Road' });
      sheet.getRange(rowIndex, sentCol + 1).setValue('Sent · ' + new Date().toISOString());
      Logger.log('Sent: ' + recipient);
      sent++;
    } catch (err) {
      Logger.log('Error sending to ' + recipient + ': ' + err.message);
    }
  });

  Logger.log('sendFollowUpEmails done. Sent: ' + sent);
}

// ── Test helper (run manually to verify sheet access) ────────────────────────
// Select this function in the editor and click Run to check everything is wired
function testSetup() {
  const ss    = SpreadsheetApp.openById(SHEET_ID);
  const sheet = ss.getSheetByName(SHEET_NAME);
  Logger.log('Sheet found: ' + sheet.getName());
  Logger.log('Last row: '    + sheet.getLastRow());
}
